language: minimal
root: yes
services:
- docker
dist: xenial
os: linux
jobs:
  include:
  - stage: Build
    arch: s390x
    script: "./ci/build-and-push-latest-with-arch.sh"
    env: DOCKER_FILE=Dockerfile-s390x
  - arch: amd64
    script: "./ci/build-and-push-latest-with-arch.sh"
    env: DOCKER_FILE=Dockerfile-x86
  - arch: ppc64le
    script: "./ci/build-and-push-latest-with-arch.sh"
    env: DOCKER_FILE=Dockerfile-ppc64le
  - stage: Manifest
    arch: amd64
    script:
    - sudo bash ci/enable-experimental.sh
    - sudo bash ci/manifest-create-and-push.sh
env:
  global:
  - DOCKER_IMAGE=bendermibm/manifest-example
  - DOCKER_REGISTRY=registry.hub.docker.com
  - secure: CF1K4rZV9YmkqzcNikgCj+y3M9bS3uKrxliMamzIusSaViK6UbW68SEpZy4tqoh0xutuBdazbz/WJ8oDLLU56wpoTFzLtCZOeiMgpq7ihwbIzaTIV7KkbD0zRXZ22ijK9HxTGyLANwmtmnoehRml0UZ/2SZrXGiKhLkqVrPc7ZxX9ssAqFR3td2CLvshiwKLPMVYLKrxIXN3KiFWNrrSZJy7seTUz6roIistrG1Zxz8A0ZlbWJmBs5BXg4woo3gofjzJGO94AwYc1i5WFm7NeBoFv5QDzs7/z3ImVqwphl7LOqvyUw3j24ju5FipgALLapdtfYnFUdV1pAHKiYVSHJ1OS8F/elaoIDLkskLlXoLv9j7U/A/W93BgVrIMgoOBk+YmYY8c6aoWbvsQuVclBxWVA2GcrKAFYGRpdD8nroqorjhQOJdmSzv/JYA9Us7HIK6fl9PcxAp79F9H+DFr6IvZ6TpKKF3/49ACuwCnZ2st532iT+y2gaEST/u4Mj6giSHnt1tEJFpkhyr1hHPn1rkWpvAFQwPIR3WyeaVKD1OUNipxTleoINC9gKwVAWNtXLTEUfoftSLXJsIr1RM8VRMBDfGSm0fzSVRSolFFbVFmAwKwTJnhq1RafYWFNcn35iXjhRe4tNPl6pd+91iNtFLQ9lPRFCqEJeiUW+Keyos=
  - secure: jiJJQTIHUgYlpuW+ih4OgKehRkSKbNlxMvr7VXl5UbSE8XY9W7d0wKCVsJSjkYX/CvetetmKFvdAkXOA84Xec7aTfE+2AQ+ditVotNwE8NybByzd7KUL+McjSmCxc2rgL8519bNjRiZamqmxB2D/BdyiyJFhDmJR7y5+eA+KtwfI3kafyG7H09uOnswgnZ7tuoPOHAAGSNBAifyDJGZ59px29WwISvS8jx37htDgOx7UVdB/HiVtz3Cfe5/Zrx09C/obp83gaYfpv430uNBHcdrflBUI//MhKFo0Zc/iYavf2iud5KwHJz991okvHnckK0N8B8SEMwBS8lfYsTEeleR+MT1thgY3mZT4bK9Nz7rz/zFQs4Ky/zRoH3U9ZmzIEirDkJu2JzUEvesTJ4mLjfro7vYIsObUdMx5s6eHFYDn00yiDHlozK8qInJHRcqiCh81Wvd1yzgU+WH0suH4MK5pVQstN6IpGAJCmCi7L85pbXXmnbN+8TnyrLRJ7eEWOj9grJtlO3u5G0koz6tM1UGm9y9aDqOhMHeeDvvHvXSEh3Rl3893TOg2OWd/6HfRQrod6wY8riH/1UcC/+q8GkFQ1k/w797P81iiPcgkHLrbX/X/QZ64VmpL8B3Sy57mTYMxy/TCHaM8I3boE9joahFOzn81qGAsicqHPz0Ha+0=
notifications:
  slack:
    secure: hdEtqhIvjdjwvB1zejb+4WvIpaNmE3GtkGlZah9Xiq1gN/mp18PW0FY0ctXDuAxZVYF4YALlltOwR8dkjNsmoL0l3xI9EKwBtSSQBWqe/SZS1/3w7DDnf6SoABr9bWOJK+ObBy1yDFmgsxNWN9V6qAZmqNEuJcoHlNm/wj+uk1yfhO6RjHlD7HfmHEO52rTVlQqcPlXW5laXd1G6GGwwCvrtqY6pAJj1LxkCnhwPL/Ikm+UcdBoaoJcpB/b6fesw38V0uZB1JqE1NQm6Elv6M/AAknawqbSekBTcff1U7iuG7cRK4V6NSLl65s108eRtST61Veuvk25yr/YUVAyU3FyxBiJ3Ref0UaeEl6P0ERa/FeewjH0H7Rnj3FrMMO1lL6lDodU5Eyv7UhhfAXiXp1aDIqEbNBdmxtYDFEtBF12/S+o+wmyJ1nQMkHFp66kwz+jeDUKSoTeP6ouTMfxl/OPdTK/QGrSG/wwO7lVs3L4rGK/SZukpImELn5Is/0745yvOXIkuIaxXggYpB+j39AGvACrNHx5W1T897SuqcFG/NCmcxY6xPdPUfetJsdiLyJnOuoy7UGfODY7UDR7xnkTfCNuA/Z4+wCTszFGGYwuljF9q+tkIncT0zfmJxBkK/K6+eeAvroMyHup3Xr3WZ70heSf01Cs2KPDtTnPWoj4=
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}
      by %{author} %{result} in %{duration}. ```%{docker_image}:%{build_id}```
